backends/quartz/quartz_database.cc: For cygwin, use the underlying MoveFile API call for locking, as link() doesn't work on FAT partitions.  And don't rely on HAVE_LINK to control whether we use link() otherwise - if the configure test somehow misfires, a compilation error is better than using rename() on Unix as that would cause a second writer to smash the lock of the first.
git-svn-id: https://svn-dav.xapian.org:8443/xapian/trunk@5800 6b2f1b92-a4f3-0310-943f-de3cbe41748b