common/safeunistd.h: Add '#include <sys/types.h>' so that we've seen a typedef for off_t before we hide it behind a #define to avoid a compilation error if <sys/types.h> or <wchar.h> is included after we are.
git-svn-id: https://svn-dav.xapian.org:8443/xapian/trunk@7607 6b2f1b92-a4f3-0310-943f-de3cbe41748b