expand/ortermlist.cc,expand/ortermlist.h: Fix compilation error when --enable-assertions is used.
git-svn-id: https://svn-dav.xapian.org:8443/xapian/trunk@8432 6b2f1b92-a4f3-0310-943f-de3cbe41748b